[package]
name = "chalk"
version = "0.10.1-dev"
description = "Model of the Rust trait system"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]
edition = "2018"
publish = false

[features]
bench = []

[dependencies]
docopt = "1.1.0"
itertools = "0.9.0"
rustyline = "6.0.0"
salsa = "0.10.0"
serde = "1.0"
serde_derive = "1.0"

chalk-macros = { version = "0.10.1-dev", path = "chalk-macros" }
chalk-derive = { version = "0.10.1-dev", path = "chalk-derive" }
chalk-engine = { version = "0.10.1-dev", path = "chalk-engine" }
chalk-ir = { version = "0.10.1-dev", path = "chalk-ir" }
chalk-rust-ir = { version = "0.10.1-dev", path = "chalk-rust-ir" }
chalk-solve = { version = "0.10.1-dev", path = "chalk-solve" }
chalk-parse = { version = "0.10.1-dev", path = "chalk-parse" }
chalk-integration = { version = "0.10.1-dev", path = "chalk-integration" }

[workspace]
