[package]
name = "chalk-solve"
version = "0.10.1-dev"
description = "Combines the chalk-engine with chalk-ir"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]
edition = "2018"

[dependencies]
ena = "0.14.0"
itertools = "0.9.0"
petgraph = "0.5.0"
rustc-hash = { version = "1.0.0" }

chalk-macros = { version = "0.10.1-dev", path = "../chalk-macros" }
chalk-derive = { version = "0.10.1-dev", path = "../chalk-derive" }
chalk-engine = { version = "0.10.1-dev", path = "../chalk-engine" }
chalk-ir = { version = "0.10.1-dev", path = "../chalk-ir" }
chalk-rust-ir = { version = "0.10.1-dev", path = "../chalk-rust-ir" }

[dev-dependencies]
chalk-integration = { version = "0.10.1-dev", path = "../chalk-integration" }
